### ISSUE TITLE
Achievements are lagging server

### ISSUE THREAD

**Issue by Teleriann** [PyvesB/advanced-achievements#1003]
* Advanced Achievements version: newest one from https://www.spigotmc.org/resources/advanced-achievements.83466/
* Minecraft version: 1.16.5
* [Wiki](https://github.com/PyvesB/advanced-achievements/wiki) read: Yes, i have
* [Existing issues](https://github.com/PyvesB/advanced-achievements/issues) searched: Yes i have
* Spigot username: Teleriann

:beetle: **Description**

Server was running just fine, we are using achievements plugin for a longer time. But couple of days ago server started to experience lag spikes. Heavy lag spikes that tps went from 20 to 7 with 3-4seconds of lag spike. Of course that i have looked to server timings, and i found that achievements are causing unusual heavy server load. We have over 5000 achievements on our server, so we tried to reduce that to lower number, but it did not help. Iam reading our timings alot, to optimize our server performance, achievements always had like 2% of server performance, but right now, sometimes it hits 20%.

I have tried to put larger numbers in seconds to config to reduce the lag, but it did not help at all, i even tried to look for some pattern, when the server lag spikes, but it looks like that it is "random".

I will be glad for every piece of help that i could get, thank you. Also, im sorry for my english.

Timings for example: 1. https://timings.aikar.co/?id=c13a7de340b440eebc82951f6164c318#plugins 2. https://timings.aikar.co/?id=0308f55ee0234c708dd0d1f4e547f32d#plugins

:page_facing_up: **Server logs**

There are not any errors or anything like that in our console or logs, thats why i have problem to resolve that issue.
````

````

:wrench: **Configuration**

````
#======================================================================================================================#
#       _       _                               _      _        _     _                                     _          #
#      / \   __| |_   ____ _ _ __   ___ ___  __| |    / \   ___| |__ (_) _____   _____ _ __ ___   ___ _ __ | |_ ___    #
#     / _ \ / _` \ \ / / _` | '_ \ / __/ _ \/ _` |   / _ \ / __| '_ \| |/ _ \ \ / / _ \ '_ ` _ \ / _ \ '_ \| __/ __|   #
#    / ___ \ (_| |\ V / (_| | | | | (_|  __/ (_| |  / ___ \ (__| | | | |  __/\ V /  __/ | | | | |  __/ | | | |_\__ \   #
#   /_/   \_\__,_| \_/ \__,_|_| |_|\___\___|\__,_| /_/   \_\___|_| |_|_|\___| \_/ \___|_| |_| |_|\___|_| |_|\__|___/   #
#                                                                                                                      #
#======================================================================================================================#

# Only spaces, no tabs. Don't forget the indents (2 spaces per indentation level).
# To check syntax errors in your file, use: https://yaml-online-parser.appspot.com
# To get involved with the project, visit its GitHub: https://github.com/PyvesB/advanced-achievements
# To get some valuable additional documentation, visit the Wiki: https://github.com/PyvesB/advanced-achievements/wiki
# The default configuration files can be found at the following address:
# https://github.com/PyvesB/advanced-achievements/blob/master/advanced-achievements-plugin/src/main/resources/config.yml

#======================================================================================================================#
#                                                   GENERAL SETTINGS                                                   #
#                                                                                                                      #
#                                Various settings to fine-tune the plugin's behaviour.                                 #
#======================================================================================================================#

# Time in seconds between each /aach book. Ignored for players with achievement.* permission.
TimeBook: 900

# Sort pages of the book in chronological order (false for reverse chronological order).
BookChronologicalOrder: true

# Separator between name, description and date on an /aach book page.
BookSeparator: ""

# Activate firework effects when a player receives an achievement.
Firework: true

# Choose ball_large, ball, burst, creeper, star or random.
FireworkStyle: ball_large

# Activate simpler effects and a calm sound when a player receives an achievement. Ignored if Firework setting is true.
SimplifiedReception: false

# Number of players displayed in /aach top, week and month commands.
TopList: 5

# Activate particle effects when performing /aach book, /aach stats when all achievements have been received and
# /aach top, week or month when ranked in the top list.
AdditionalEffects: true

# Activate sounds when performing /aach book, /aach stats when all achievements have been received and  /aach top, week
# or month when ranked in the top list.
Sound: true

# For /aach book. All sound values can be found here: https://github.com/PyvesB/advanced-achievements/wiki/Sound-names
SoundBook: entity_player_levelup

# For /aach stats when all achievements have been received.
SoundStats: entity_firework_rocket_blast

# For /aach top, week, month when ranked in the top list.
SoundRanking: entity_firework_rocket_blast

# Icon of the plugin (default: shamrock, \u2618).
Icon: CZS

# Main color of the plugin (default: 5, dark purple).
Color: 5

# Notify other connected players when an achievement is received. This defines the default behaviour, players can
# override what they see by using /aach toggle.
NotifyOtherPlayers: false

# Notify other connected players using action bars, otherwise chat messages are used.
ActionBarNotify: true

# Display achievement DisplayName and Message as screen titles. Minimum Minecraft version: 1.8.
TitleScreen: true

# Send informative chat messages to the player receiving an achievement.
ReceiverChatMessages: true

# When a player receives an achievement, the DisplayName, Message and rewards of the achievement are displayed in the
# chat as separate messages. If true, a single hoverable text will be displayed to the receiver instead.
HoverableReceiverChatText: true

# Format of the header used for most chat messages (default: "§7[%ICON%§7]"). Can be empty, "".
ChatHeader: "§7[%ICON%§7]"

# Stop all stats from increasing when player in creative mode, including PlayedTime. Connection achievements will only
# be handled once a player switches to a non-creative mode.
RestrictCreative: false

# Stop all stats from increasing when player in spectator mode, including PlayedTime. Connection achievements will only
# be handled once a player switches to a non-spectator mode. Minimum Minecraft version: 1.8.
RestrictSpectator: true

# Stop all stats from increasing when player in adventure mode, including PlayedTime. Connection achievements will only
# be handled once a player switches to a non-adventure mode.
RestrictAdventure: false

# Stop all stats from increasing when player in a specific world, including PlayedTime (delete the [] before listing
# values). Connection achievements will only be handled once a player enters a non-excluded world.
ExcludedWorlds: []
#  - yourWorld1
#  - yourWorld2

# Ignore vertical dimension (Y axis) when calculating distance statistics.
IgnoreVerticalDistance: false


# Do not take into account items broken with Silk Touch for the Breaks achievements.
DisableSilkTouchBreaks: false

# Do not take into account ores broken with Silk Touch for the Breaks achievements. DisableSilkTouchBreaks takes
# precedence over this. Not applicable to iron or gold ores.
DisableSilkTouchOreBreaks: false

# Language file to use. Available: lang.yml, lang-BP.yml, lang-CN.yml, lang-CZ.yml, lang-DA.yml, lang-DE.yml,
# lang-ES.yml, lang-FI.yml, lang-FR.yml, lang-HU.yml, lang-IT.yml, lang-PL.yml, lang-RO.yml, lang-RU.yml, lang-SE.yml,
# lang-SK.yml, lang-TR.yml, lang-TW.yml, lang-VN.yml
LanguageFileName: lang.yml

# Time in seconds between each statistic count. Only the listed categories are currently supported.
StatisticCooldown:
  LavaBuckets: 10
  WaterBuckets: 10
  Milk: 10
  Beds: 30
  Brewing: 5
  MusicDiscs: 30

# Display action bar message when player performs an action while in a cooldown period. Minimum Minecraft version: 1.8.
CooldownActionBar: true

# Locale used to format dates in /aach book and /aach list. You must select an ISO 639 language code. The list of
# possible language codes can be found at https://www.loc.gov/standards/iso639-2/php/code_list.php
DateLocale: cs

# Display reception time of achievements in /aach book and /aach list in addition to the date.
DateDisplayTime: true

# Check for update on plugin launch and notify when a player with achievement.update permission joins the game.
CheckForUpdate: true
# PlayedTime will no longer increase when the player is AFK. Requires Essentials to work.
IgnoreAFKPlayedTime: false

# Register advancements with a description corresponding to the Goal parameter of each achievement. If changed, run
# /aach generate to regenerate advancements with the new value taken into account. Minimum Minecraft version: 1.12.
RegisterAdvancementDescriptions: true

# Hide advancements from the advancement GUI. Advancement notifications will still appear when receiving achievements.
# Minimum Minecraft version: 1.12.
HideAdvancements: true

# Title shown on the root advancement.
RootAdvancementTitle:  

# Background shown on the advancement tab. Must be a resource location to any image in a resource pack.
AdvancementsBackground: "minecraft:textures/item/book.png"

#======================================================================================================================#
#                                                     GUI SETTINGS                                                     #
#                                                                                                                      #
#        Configure the behaviour of /aach list. The items being displayed can be further customised in gui.yml.        #
#======================================================================================================================#

# Format of the achievement category name in /aach list (default: "%ICON% %NAME% %ICON%").
ListAchievementFormat: "%NAME%"

# Obfuscate achievements that have not yet been received in /aach list.
ObfuscateNotReceived: false

# For Multiple action achievement categories with a series of related achievements, show achievements that have been
# obtained and show the next obtainable achievement, but obfuscate the additional achievements. For example, under
# Places, stone, the first achievement could have a target of 100 stone, the second 500 stone, and the third 1000 stone.
# When ObfuscateProgressiveAchievements is true, initially only the 100 stone achievement will be readable in the GUI.
# Once 100 stone have been placed, the 500 stone achievement will become legible.
ObfuscateProgressiveAchievements: false

# Similar to ObfuscateProgressiveAchievements, but displays not received achievements as locked in /aach list.
HideProgressiveAchievements: false

# Hide categories for which a player has not yet received achievements by displaying them as locked in /aach list.
HideNotReceivedCategories: false

# Completely hide categories for which the player does not have the matching permission (e.g. achievement.count.beds).
HideNoPermissionCategories: false

# Hide the reward display in /aach list.
HideRewardDisplayInList: false

# Display precise statistic information in the /aach list progress bars.
EnrichedListProgressBars: true

# Annotate each achievement displayed in a /aach list category with a number.
NumberedItemsInList: false

# Color used for not yet received achievements in /aach list.
ListColorNotReceived: 8

# Italicise not yet received achievements in /aach list. Obfuscated achievements are not affected.
ListItaliciseNotReceived: true

# By default, the back button in the GUI returns to the listing of all categories. Use this option if you want to run a
# command instead. PLAYER placeholder is supported.
OverrideBackButtonBehaviour: ""

# If true, the icon of the back button in the GUI will be the same as the category currently being viewed.
BackButtonIsCategoryItem: true

#======================================================================================================================#
#                                                  DATABASE SETTINGS                                                   #
#                                                                                                                      #
#                       The database is where all player statistics and achievements are stored.                       #
#======================================================================================================================#

# Make a daily backup of your local database (if sqlite or h2).
DatabaseBackup: true

# Database type, sqlite, h2, postgresql or mysql. Do a full server restart for this to take effect.
DatabaseType: MySQL

# Prefix added to the tables in the database. If you switch from the default tables names (no prefix),
# the plugin will attempt an automatic renaming. Otherwise you have to rename your tables manually.
# Do a full server restart for this to take effect.
TablePrefix: ''

# Specify additional options when opening a connection to a MySQL/PostgreSQL database. Start each option with &,
# for instance "&useUnicode=yes&characterEncoding=UTF-8". Make sure the key-value pairs themselves are URL encoded.
AdditionalConnectionOptions: '&autoReconnect=true&useSSL=false'

# Settings to connect to your MySQL/PostgreSQL database (ignored if sqlite).
# A PostgreSQL database address will be similar to jdbc:postgresql://localhost:5432/minecraft
DatabaseAddress: WE ARE CONNECTED TO DATABASE
DatabaseUser: 
DatabasePassword:

#======================================================================================================================#
#                                                 PERFORMANCE SETTINGS                                                 #
#                                                                                                                      #
#                                    In most cases, you won't need to change these.                                    #
#======================================================================================================================#

# Frequency of play time checks for players (seconds). Smaller values give more precision but more CPU usage.
PlaytimeTaskInterval: 800

# Frequency of distance traveled checks by players (seconds). Smaller values give more precision but more CPU usage.
DistanceTaskInterval: 180

# Enable if you use BungeeCord or if your database is shared by multiple servers. Do a full server restart.
BungeeMode: false
````
