### ISSUE TITLE
Jobs Reborn hook

### ISSUE THREAD

**Issue by Teyir** [PyvesB/advanced-achievements#1014]
Bonjour,

j'ai un petit soucis avec le JobsReborn, aach ne prend pas en compte les levels de jobsreborn.

Voici ma config:

````

JobsReborn:
  lumberjack:
    10:
      Goal: Passer lvl 10 Bûcheron.
      Message: §aPasse lvl 10 Bûcheron!
      Name: jobsreborn_10_lumberjack
      DisplayName: LVL 10 Bûcheron!
      Type: normal
      Reward:
        Command:
          Execute: give PLAYER iron_axe
 
````

![image](https://user-images.githubusercontent.com/60007549/116859840-ee203e00-ac00-11eb-96c8-ee080f647e88.png)

![image](https://user-images.githubusercontent.com/60007549/116859857-f37d8880-ac00-11eb-8847-4ad7b2814007.png)

Voilà, merci beaucoup pour votre aide
