### ISSUE TITLE
Add achievements "rarity"/"category"?

### ISSUE THREAD

**Issue by Krosta8** [PyvesB/advanced-achievements#452]
Hello,

I have an idea about "new feature".
When you create achievement in config, it would be nice to add something like "rarity" (maybe not the good explanation). For example: Categories - Simple, Moderate, Hard, Ultra, Legendary
And in the config should be 
```
categories:
 - simple: "&fSimple"
 - moderate: "&bModerate"
 - hard: "&cHard"
 - others: "&7Without category"
```
and so on.
For each achievement player has to add new row with `category: CategoryName`, without this row it will be in category `others`.

When the player open the GUI, it will show him just this five categories and then the player can see achievements, which correspondent for the category.

I hope I explained it well and it is understandable 😄
