### ISSUE TITLE
bug with jobs achievement :(

### ISSUE THREAD

**Issue by n54b** [PyvesB/advanced-achievements#889]
Error when i set up jobs : 
````
06.11 21:23:23 [Server] Server thread/ERROR A non recoverable error was encountered while loading the plugin, disabling it:
06.11 21:23:23 [Server] INFO com.hm.achievement.exception.PluginLoadError: Achievement with path (JobsReborn.chasseur.Reward) is missing its Name parameter in config.yml.
06.11 21:23:23 [Server] INFO at com.hm.achievement.config.ConfigurationParser.parseAchievement(ConfigurationParser.java:343) ~[?:?]
06.11 21:23:23 [Server] INFO at com.hm.achievement.config.ConfigurationParser.parseAchievements(ConfigurationParser.java:327) ~[?:?]
06.11 21:23:23 [Server] INFO at com.hm.achievement.config.ConfigurationParser.parseAchievements(ConfigurationParser.java:310) ~[?:?]
06.11 21:23:23 [Server] INFO at com.hm.achievement.config.ConfigurationParser.loadAndParseConfiguration(ConfigurationParser.java:89) ~[?:?]
06.11 21:23:23 [Server] INFO at com.hm.achievement.lifecycle.PluginLoader.loadAdvancedAchievements(PluginLoader.java:142) ~[?:?]
06.11 21:23:23 [Server] INFO at com.hm.achievement.AdvancedAchievements.onEnable(AdvancedAchievements.java:50) ~[?:?]
06.11 21:23:23 [Server] INFO at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[spigot-1.16.3.jar:git-Spigot-2740d5a-890130b]
06.11 21:23:23 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:351) ~[spigot-1.16.3.jar:git-Spigot-2740d5a-890130b]
06.11 21:23:23 [Server] INFO at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:480) ~[spigot-1.16.3.jar:git-Spigot-2740d5a-890130b]
06.11 21:23:23 [Server] INFO at com.rylinaux.plugman.util.PluginUtil.load(PluginUtil.java:366) ~[?:?]
06.11 21:23:23 [Server] INFO at com.rylinaux.plugman.command.LoadCommand.execute(LoadCommand.java:114) ~[?:?]
06.11 21:23:23 [Server] INFO at com.rylinaux.plugman.PlugManCommandHandler.onCommand(PlugManCommandHandler.java:95) ~[?:?]
06.11 21:23:23 [Server] INFO at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[spigot-1.16.3.jar:git-Spigot-2740d5a-890130b]
06.11 21:23:23 [Server] INFO at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:149) ~[spigot-1.16.3.jar:git-Spigot-2740d5a-890130b]
06.11 21:23:23 [Server] INFO at org.bukkit.craftbukkit.v1_16_R2.CraftServer.dispatchCommand(CraftServer.java:758) ~[spigot-1.16.3.jar:git-Spigot-2740d5a-890130b]
06.11 21:23:23 [Server] INFO at net.minecraft.server.v1_16_R2.PlayerConnection.handleCommand(PlayerConnection.java:1697) ~[spigot-1.16.3.jar:git-Spigot-2740d5a-890130b]
06.11 21:23:23 [Server] INFO at net.minecraft.server.v1_16_R2.PlayerConnection.a(PlayerConnection.java:1540) ~[spigot-1.16.3.jar:git-Spigot-2740d5a-890130b]
06.11 21:23:23 [Server] INFO at net.minecraft.server.v1_16_R2.PacketPlayInChat.a(PacketPlayInChat.java:47) ~[spigot-1.16.3.jar:git-Spigot-2740d5a-890130b]
06.11 21:23:23 [Server] INFO at net.minecraft.server.v1_16_R2.PacketPlayInChat.a(PacketPlayInChat.java:1) ~[spigot-1.16.3.jar:git-Spigot-2740d5a-890130b]
06.11 21:23:23 [Server] INFO at net.minecraft.server.v1_16_R2.PlayerConnectionUtils.lambda$0(PlayerConnectionUtils.java:19) ~[spigot-1.16.3.jar:git-Spigot-2740d5a-890130b]
06.11 21:23:23 [Server] INFO at net.minecraft.server.v1_16_R2.TickTask.run(SourceFile:18) ~[spigot-1.16.3.jar:git-Spigot-2740d5a-890130b]
06.11 21:23:23 [Server] INFO at net.minecraft.server.v1_16_R2.IAsyncTaskHandler.executeTask(SourceFile:144) ~[spigot-1.16.3.jar:git-Spigot-2740d5a-890130b]
06.11 21:23:23 [Server] INFO at net.minecraft.server.v1_16_R2.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[spigot-1.16.3.jar:git-Spigot-2740d5a-890130b]
````

:wrench: **Configuration**

````
JobsReborn:
  chasseur:
    1:
      Goal: Level up as a chasseur !
      Message: You have reached chasseur level 2!
      Name: jobsreborn_1_chasseur
      DisplayName: chasseur
      Type: normal
    Reward:
      Item: bow 1
````

**Comment by PyvesB** [comment]
Hello @n54b! :wave:

The `Reward` section is incorrectly indented. Try this instead:
```
JobsReborn:
  chasseur:
    1:
      Goal: Level up as a chasseur !
      Message: You have reached chasseur level 2!
      Name: jobsreborn_1_chasseur
      DisplayName: chasseur
      Type: normal
      Reward:
        Item: bow 1
```

**Comment by n54b** [comment]
omg -_- really ty xD 
and ty again for your answer to my email: D
Ah and I have this warning at startup: 

Server thread/WARN gui.yml (AchievementNotStarted.Item.Item) is missing. Please check your configuration.
06.11 23:23:39 [Server] Server thread/WARN gui.yml (AchievementStarted.Item.Item) is missing. Please check your configuration.
06.11 23:23:39 [Server] Server thread/WARN gui.yml (AchievementReceived.Item.Item) is missing. Please check your configuration.

**Comment by PyvesB** [comment]
Could you please share your _gui.yml_? Bits relating to `AchievementReceived`.

**Comment by n54b** [comment]
https://pastebin.com/ag82EKGc

**Comment by PyvesB** [comment]
Yeah, so the new configuration style has an extra dimension:
```
AchievementNotStarted:
  normal:
    Item: red_terracotta
  rare:
    Item: red_glazed_terracotta
AchievementStarted:
  normal:
    Item: yellow_terracotta
  rare:
    Item: yellow_glazed_terracotta
AchievementReceived:
  normal:
    Item: lime_terracotta
  rare:
    Item: lime_glazed_terracotta
```

But I'll suppress the warning, as it isn't very clear anyway.
