### ISSUE TITLE
Something... Not sure if its a bug or an config mistake.

### ISSUE THREAD

**Issue by Remski01** [PyvesB/advanced-achievements#905]
Sorry if this is the wrong place, but we have an issue that it doesnt count up in the progress bar, 

Version:
- git-Paper-138 (MC: 1.16.1)
- AA 6.7.2

setting:
```
Breaks:
  gold_ore1:
    '1000':
      Goal: Mijn 1000 gold ore.
      Message: PLACEHOLDER (GPM)1
      Name: break_1000_gold_ore
      DisplayName: Econoom 1
      Type: normal
      Reward:
        Command:
          Execute: lp user PLAYER permission set bossshop.voteshop.gpm1
          Display:
          - Krijg 1 EUR per minuut dat je online bent.
```
