### ISSUE TITLE
Config bug

### ISSUE THREAD

**Issue by LuluxClient** [PyvesB/advanced-achievements#909]
:information_source: **Basic information**

* Advanced Achievements version: 
* Minecraft version: 
* [Wiki](https://github.com/PyvesB/advanced-achievements/wiki) read: 
* [Existing issues](https://github.com/PyvesB/advanced-achievements/issues) searched: 
In the config if you put "Message: §1La première fois que vous êtes allé miner!" in a achievement, in the achievement book it won't change. : config : https://gyazo.com/48e93e04e4205cf448974bf9642130d4
Book : https://gyazo.com/f58ac272676bc9b9278736e04dd11f1a
:beetle: **Description**

You need to do the achievement, edit the name and done.
:page_facing_up: **Server logs**

````
NO ERRORS OR WARN
````

:wrench: **Configuration**

````
  stone:
    1:
      Goal: Casse un bloc.
      Message: §1La première fois que vous êtes allé miner!
      Name: break_1_stone
      DisplayName: Début de la richesse!
      Type: normal
      # Use semicolons for multiple command rewards. PLAYER will be replaced by players name.
      Reward:
        Command:
          Execute: "eco give PLAYER 1000"
          Display: 1000 pièces!
````
