### ISSUE TITLE
API: give custom achievement to player that does not exist in the config yet

### ISSUE THREAD

**Issue by Silthus** [PyvesB/advanced-achievements#990]
:information_source: **Basic information**

I have a question about the API. I want to create an additional plugin that handles location achievements and allows creating them via commands and with a radius without relying on worldguard regions, signs or other unneeded stuff.

So I want to have a database with all locations and the achievement name. By default they don't look pretty but can be customized using the given key under the custom section in the config. Is that possible?

:question: **Help request**

- Is it possible to add new custom achievement types on the fly via the API?
- How can I give a player a single custom achievement that may not exist yet and has no counter?

Thank you for the help!

*The plugin will of course be open source or if you like the idea, be integrated into the plugin itself.*

**Comment by PyvesB** [comment]
Hello @Silthus ! 👋🏻 

Thanks for your interest in this project! The overall idea sounds like a good one.

>     * Is it possible to add new custom achievement types on the fly via the API?

Unfortunately, this is not currently possible. The main blocker to doing this is the fact that achievement categories are currently modelled as enums. For example: https://github.com/PyvesB/advanced-achievements/blob/master/advanced-achievements-api/src/main/java/com/hm/achievement/category/MultipleAchievements.java

This makes achievement types very static. I don't think it would too hard to change this though, it's mostly a matter of turning the enum into a class to which new categories can dynamically be added.

>     * How can I give a player a single custom achievement that may not exist yet and has no counter?

I'm going to disappoint you as well, achievements are currently only driven by _config.yml_. However, some of the refactoring that was conducted as part of the 7.0.0 release would allow to do this much more easily, as it would be a matter of adding achievements to `AchievementMap`.

I'm unsure how you would specify all the parameters (`Type`, `Goal`, etc.) and rewards for a dynamic achievement. You mentioned creating achievements via commands in your third-party plugin, I can't imagine it being practical to include all the information for an achievement.

In the meantime, an alternative would be to leverage the _Commands_ or _Custom_ categories, append new achievements to Advanced Achievements' _config.yml_ for one of those categories, and call _/aach reload_. Admittedly clunky, but it should work fine.

I'm sorry I'm not able to provide a perfect solution, but let me know whether this information helps! 😉

**Comment by Silthus** [comment]
Hi @PyvesB 

thank you for the detailed and quick reply. However I think the current API does make it possible what I thought of. Here is a code snipped on how I thought it might work:

```java
AdvancedAchievementsAPI api = ...;

String category = "locations";
String identifier = "loc1";
String name = "Super dupa location";
String message = "You reached the super location";
Achievement achievement = api.getOrCreateAchievement(category, identifier, name, message);
// or use the achievement builder and then register the achievement
Achievement achievement = api.registerAchievement(new AchievementBuilder()....build());
// or get an existing achievement from the plugins category
Achievement achievement = api.getAchievement(category, identifier);

api.addAchievement(achievement, player);
```

And in the `config.yml` a new block is created for each achievement created via the API, maybe under a new `plugins` category?

```yaml
...

Custom:
  votes:
    10:
      Message: Voted 10 times for the server!
      Name: customs_votes_10
      DisplayName: Server fan
      Type: normal
      Reward:
        Money: 5

Plugins:
  locations:
    loc1:
      Name: loc1
      DisplayName: Super dupa location
      Message: You reached the super location
      # the rest are defaults that are filled in
      Type: normal
      Reward: {}
```

What do you think?
